### CURRENTS - Latest Geopolitical News
GET https://api.currentsapi.services/v1/search?keywords=geopolitics&language=en&page_size=10
Authorization: dBcWlBKRQlN1iOwHaxVca7vPGMmhDXLj7A3domkSe5OHAjnc
Accept: application/json

### CURRENTS — CONFLICT
GET https://api.currentsapi.services/v1/search?keywords=conflict&language=en&page_size=10
Authorization: dBcWlBKRQlN1iOwHaxVca7vPGMmhDXLj7A3domkSe5OHAjnc
Accept: application/json


### CURRENTS — MILITARY
GET https://api.currentsapi.services/v1/search?keywords=military&language=en&page_size=10
Authorization: dBcWlBKRQlN1iOwHaxVca7vPGMmhDXLj7A3domkSe5OHAjnc
Accept: application/json

### CURRENTS — DIPLOMACY
GET https://api.currentsapi.services/v1/search?keywords=diplomacy&language=en&page_size=10
Authorization: dBcWlBKRQlN1iOwHaxVca7vPGMmhDXLj7A3domkSe5OHAjnc
Accept: application/json

### CURRENTS — SANCTIONS
GET https://api.currentsapi.services/v1/search?keywords=sanctions&language=en&page_size=10
Authorization: dBcWlBKRQlN1iOwHaxVca7vPGMmhDXLj7A3domkSe5OHAjnc
Accept: application/json


### CURRENTS — INDIA
GET https://api.currentsapi.services/v1/search?keywords=India&language=en&page_size=10
Authorization: dBcWlBKRQlN1iOwHaxVca7vPGMmhDXLj7A3domkSe5OHAjnc
Accept: application/json